//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using System;

namespace AssemblyCSharp
{
		[TestFixture()]
		public class TestCases
		{

				[Test()]
				public void TestInitHP ()
				{
			Agent7StatsUI A = new Agent7StatsUI ();
			int a = A.getHp ();
		//	Console.WriteLine (a);
			int b = 2;
			Assert.AreEqual (a, b);
				}

				[Test()]
				public void TestNewHP ()
				{
			Agent7StatsUI A = new Agent7StatsUI ();
			A.setHp (1);
			int a = A.getHp ();
		//	Console.WriteLine (a);
			int b = 1;
			Assert.AreEqual (a, b);
				}

		[Test()]
				public void TestNewScore ()
				{
			Agent7StatsUI A = new Agent7StatsUI ();
			A.setScore (2);
			int a = A.getScore();
		//	Console.WriteLine (a);
			int b = 2;
			Assert.AreEqual (a, b);
				}


		[Test()]
				public void TestScoreZero ()
				{
			Agent7StatsUI A = new Agent7StatsUI ();
			A.setScore (-1);
			int a = A.getScore ();
		//	Console.WriteLine (a);
			int b = 0;
			Assert.AreEqual (a, b);
				}

		}
}

